export const projects = [
  {
    title: 'Viktoria Shvoren shop',
    description: "Abstract art of Viktoria Shvoren for sale.",
    image: '/images/shvoren.jpg',
    tags: ['JavaScript', 'React', 'HTML', 'CSS'],
    source: 'https://gitlab.com/llirikk/vs_client',
    visit: 'https://elastic-meninsky-e47edb.netlify.app/',
    id: 0,
  },
  {
    title: "Kipol's audio-visual promo website",
    description: "This was my personal portfolio website that has all my audio-visual experience.",
    image: '/images/portfolio.jpg',
    tags: ['JavaScript', 'React', 'HTML', 'CSS'],
    source: 'https://gitlab.com/llirikk/kipol_site',
    visit: 'https://confident-jang-29f63e.netlify.app/',
    id: 1,
  },
  {
    title: 'Merculova Architects',
    description: "Personal website of architect Anastasia Merkulova.",
    image: '/images/abs.jpg',
    tags: ['HTML', 'CSS', 'JQuery'],
    source: 'https://gitlab.com/llirikk/merkulova_html',
    visit: 'https://nervous-goldberg-bc7944.netlify.app/',
    id: 2,
  },
  {
    title: 'DAO Concept',
    description: "Hero page with three.js 3d model animation.",
    image: '/images/eb.jpg',
    tags: ['JavaScript', 'Three.js', 'HTML', 'CSS'],
    source: 'https://github.com/llirikkcoder/html_dao',
    visit: 'https://flourishing-dodol-d12c3b.netlify.app/',
    id: 3,
  },
  {
    title: 'MediaHub',
    description: "Website development for an online cinema.",
    image: '/images/kino.jpg',
    tags: ['JavaScript', 'React', 'HTML', 'CSS'],
    source: 'https://gitlab.com/llirikk/mediahub/-/tree/master',
    visit: 'https://mediahub.surge.sh',
    id: 3,
  },
  // {
  //   title: 'Lenovo SNAPit',
  //   description: "Lenovo SNAPit Camera was one of the finest OEM camera apps back in those days. It had tonnes of unique and amazing features. I ported it to work on almost all devices at that time.",
  //   image: '/images/snapit.jpg',
  //   tags: ['Java', 'Libs', 'Smali'],
  //   source: '#',
  //   visit: 'https://forum.xda-developers.com/t/app-port-6-0-lenovo-snapit-camera-5-8-53-for-all-devices.3608065/',
  //   id: 3,
  // },
  // {
  //   title: 'CyanogenOS Apps',
  //   description: "CyanogenOS 12.1 had a set of exclusive apps like a new theme engine and a new Truecaller integrated dialer. I ported it to work with CyanogenMod 13 and CM 13 based ROMs.",
  //   image: '/images/capps.jpg',
  //   tags: ['Java', 'Libs'],
  //   source: '#',
  //   visit: 'https://forum.xda-developers.com/t/c-apps-v2-unofficial-6-0-x-cyanogen-os-capps-v2-for-cm13-and-cm13-based-roms.3254865/',
  //   id: 3,
  // },

];

export const TimeLineData = [
  { year: 2016, text: 'Started my journey as a new developer.', },
  { year: 2017, text: 'Worked intensively on ROMs & Kernels.', },
  { year: 2018, text: 'Learned Android app development.', },
  { year: 2019, text: 'Finished Diploma in Computer Engineering.', },
  { year: 2020, text: 'Got a scholarship from the Delhi government.', },
  { year: 2021, text: 'Still trying to figure out this weird year.', },
];